[package]
name = "tower-assembler"
description = "Collection of the Tower architecture assembler and microassembler tools."
version = "0.1.0"
authors = ["janstaffa"]
edition = "2021"


[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
regex = "1.6.0"
chrono = "0.4.22"